title: Assumptions of Physics
email: info@assumptionsofphysics.org
description: A research project led by Christine Aidala and Gabriele Carcassi at the University of Michigan
google_analytics:
theme: minima
future: true

collections:
  essays:
    output: true
    permalink: /essays/:path
  problems:
    output: true
    permalink: /problems/:path

defaults:
  - scope:
      path: ""
      type: "problems"
    values:
      layout: "problem"
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "article"
