title: Assumptions of Physics
description: A research project led by Christine Aidala and Gabriele Carcassi at the University of Michigan
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman